name: open_url
description: Open a URL on the user's default application. Helpful on DartVM, on Flutter use url_launcher instead.
version: 2.0.0-nullsafety.0
homepage: https://github.com/renatoathaydes/open_url
author: renato <renato@athaydes.com>

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13
